### ISSUE TITLE
Framebuffer does not actually display on Mojave

### ISSUE THREAD

**Issue by LoganDark** [samizzo/pixie#2] opened 2018-11-07 01:05 UTC
Code:
```cpp
#include "pixie/pixie.cpp"
#include "pixie/imgui.h"
#include "pixie/font.h"

using Pixie::ImGui;

int main() {
	Pixie::Font font;

	if (!font.Load("../pixie/font.bmp", 9, 16)) {
		return 1;
	}

	Pixie::Window window;

	if (!window.Open("Hello, World!", 640, 480)) {
		return 1;
	}

	while (!window.HasKeyGoneUp(Pixie::Key_Escape)) {
		ImGui::Begin(& window, & font);

		if (ImGui::Button("Hello, World!", 0, 0, 9 * 13, 16)) {
			ImGui::Label("Hello, World!", 0, 16, 0);
		}

		ImGui::End();

		if (!window.Update()) {
			break;
		}
	}

	window.Close();
}
```

CMakeLists.txt (don't kill me for using CMake):

```cmake
cmake_minimum_required(VERSION 3.12)
project(pixie_test)

set(CMAKE_CXX_STANDARD 11)

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -framework CoreGraphics -framework AppKit")

add_library(pixie pixie/pixie.cpp)
add_library(pixie_osx pixie/pixie_osx.mm)
add_library(pixie_imgui pixie/imgui.cpp)
add_library(pixie_font pixie/font.cpp)

add_executable(pixie_test main.cpp)

target_link_libraries(pixie_test pixie pixie_osx pixie_imgui pixie_font)
```

Window:

![image](https://user-images.githubusercontent.com/4723091/48103847-cdb8c980-e1e5-11e8-8be3-e7573784d657.png)

That's it.

No display.

However, I CAN still press the button, and if I add a print in there (actually `std::cout << ...`) it will display something in the terminal. I just... can't see the button. Yay.

**Comment by samizzo** [comment] 2018-11-07 03:53
Hey thanks for checking this project out! I haven't really advertised it anywhere so no one else is using it or testing it under OSX and I'm mostly using it under Windows. I *did* just use it in another project earlier today in OSX and it was working but I'm not on Mojave. I will look into it, thanks!

**Comment by LoganDark** [comment] 2018-11-07 03:54
You're welcome!

**Comment by samizzo** [comment] 2018-11-13 04:38
Hey, I just upgraded to Mojave and used your CMake file and test program. It built and ran fine; I see the "Hello, World!" button. I just realised that there is an issue with your code though - the `ImGui::Button` only returns true when the button was pressed, not while it is being pressed down, so the `ImGui::Label` will only appear for one frame then disappear. However, that's unrelated to your main issue.

Interestingly, when I set up Mojave, I selected the dark theme, but my Pixie window has a light coloured title bar whereas yours has a dark one:

![screen shot 2018-11-13 at 3 35 35 pm](https://user-images.githubusercontent.com/1753040/48391294-0d3d6380-e75a-11e8-8780-5f437660b51a.png)
Is there anything else you can tell me about your Mac setup?

**Comment by LoganDark** [comment] 2018-11-13 04:40
> the `ImGui::Button` only returns true when the button was pressed, not while it is being pressed down, so the `ImGui::Label` will only appear for one frame then disappear

@samizzo I know this.

In the future, please keep to one issue at a time. **That doesn't matter.** I don't need someone else reviewing code I slapped together for a simple fucking test! It's a DEBUG PRINT. It's not supposed to do anything useful, be user friendly or any of that. It's supposed to let me know that things WORK. And it DID, if you'll read the main post, "I CAN still press the button, and if I add a print in there [...] it will display something in the terminal"

P.S. written with other emotional issues, please don't take this as a personal attack.

> Is there anything else you can tell me about your Mac setup?

I have a Retina display - you clearly don't, so I think that's the issue...

**Comment by samizzo** [comment] 2018-11-13 04:47
Ah yes the Retina could be an issue. I'll try on my wife's Retina MBP tonight! I was working on a 2014 Mac Mini.

**Comment by LoganDark** [comment] 2018-11-13 04:48
Yeah, `tigr` (another framebuffer library I was using before finding this one) needs a special mode to work with Retina or else mouse input and pixel display gets messed up. Maybe you need to adjust the coordinates for where the pixels are drawn in the window, or something like that...

**Comment by samizzo** [comment] 2018-11-18 02:39
I managed to get some time on my wife's Retina MBP. It's not running Mojave, it's running Yosemite (10.10.5). I could only install Xcode 7.2.1 because of that, which means the highest macOS SDK I could build against was 10.11.2. I couldn't reproduce the issue, but maybe it's also related to the macOS and Xcode version.

One thing I realised from your screenshot and her machine is that the window size is 1280x960 even though we specified 640x480. I assume this is because the Retina MBP by default runs in a pixel doubled configuration.

I looked at the `tigr` source code but their Retina code is specifically related to OpenGL and I'm not using OpenGL for the backend here (although I should because I think the performance would be better).

So I'm still none the wiser about this bug. I'd like to get to the bottom of it. What are your Mac's specs? If you could send a screenshot of the "About this Mac" screen that would have everything useful I think. I'll see if I can find someone locally who has a similar machine.

Btw I pushed some small fixes. One was to avoid doing BGR -> RGB conversion and instead just set up the CG backing bitmap to be in the correct pixel order. I don't think it'll make any difference, but I suppose it's worth trying it just in case.

**Comment by LoganDark** [comment] 2018-11-18 02:42
> the window size is 1280x960 even though we specified 640x480

Yes, that's good. That means the window is the same size, and the buffer is also Retina. That's good!

> If you could send a screenshot of the "About this Mac" screen that would have everything useful I think

![image](https://user-images.githubusercontent.com/4723091/48668020-62e67880-ea98-11e8-8278-8d3ad207531c.png)

> I don't think it'll make any difference, but I suppose it's worth trying it just in case

![image](https://user-images.githubusercontent.com/4723091/48668037-ba84e400-ea98-11e8-8c60-95caa3235342.png)

**Comment by samizzo** [comment] 2020-05-23 15:10
I finally saw this happening, as I had to update my Mac Mini to Mojave. This is now fixed in commit ef4be290cffbabf0bbb7054dd04a009e63a0d785.

**Closed as completed** 2020-05-23 15:10 UTC

**Comment by LoganDark** [comment] 2020-05-23 22:35
Your commit message is a bit inaccurate, since this happened on even the first Mojave beta, but thank you :P

Now **never update to Catalina ever**

**Comment by samizzo** [comment] 2020-05-24 02:37
Hah, I'll try to avoid it but sometimes Apple makes it impossible :(
